<?php

namespace AppBundle\Repository;

/**
 * CategoryPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
