<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderItems($sortBy = 'createdAt', $in = 'desc', $category = null)
    {
        if ($category == null)
        {
            return $this->createQueryBuilder('i')
                ->where('i.quantity <> 0')
                ->orderBy("i.{$sortBy}", "{$in}");
        }
        else if (is_numeric($category))
        {
            return $this->createQueryBuilder('i')
                ->where('i.category = :category')
                ->where('i.quantity <> 0')
                ->setParameter('category', $category)
                ->orderBy("i.{$sortBy}", "{$in}");
        }
    }


    public function userItems($id)
    {
        return $this->createQueryBuilder('i')
            ->select('i')
            ->where("i.user = $id");
    }
}
