<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderItems($sortBy = 'createdAt', $in = 'desc', $category = null)
    {
        if ($category == null)
        {
            return $this->createQueryBuilder('i')
                ->where('i.quantity <> 0')
                ->andWhere('i.deletedAt IS NULL')
                ->andWhere('i.isLive = 1')
                ->orderBy("i.{$sortBy}", "{$in}");
        }
        else if (isset($category))
        {
            return $this->createQueryBuilder('i')
                ->where('i.category = :category')
                ->andWhere('i.quantity <> 0')
                ->andWhere('i.deletedAt IS NULL')
                ->andWhere('i.isLive = 1')
                ->orderBy("i.{$sortBy}", "{$in}")
                ->setParameter('category', $category);
        }
    }

    public function getAllItems()
    {
        return $this->createQueryBuilder('i')
            ->select('i')
            ->where('i.deletedAt IS NULL')
            ->andWhere('i.isLive = 1')
            ->getQuery()
            ->getResult();
    }

    public function userItems($id)
    {
        return $this->createQueryBuilder('i')
            ->select('i')
            ->where("i.user = $id")
            ->leftJoin('i.itemDiscount', 'itemDiscount')
            ->addSelect('itemDiscount.discount')
            ->andWhere('i.deletedAt IS NULL')
            ->orderBy('i.createdAt', 'DESC');
    }

}
