<?php

namespace AppBundle\Repository;

/**
 * ItemPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
